# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ManMon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='income',
            name='earning',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='buy_thing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='payment_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManMon.Payment'),
        ),
    ]
