# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManMon', '0003_income_pub_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='pub_date',
            field=models.DateField(auto_now=True),
        ),
    ]
