# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManMon', '0006_auto_20170219_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incometype',
            name='income_list',
        ),
        migrations.RemoveField(
            model_name='paymenttype',
            name='payment_list',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='pub_time',
        ),
        migrations.AlterField(
            model_name='payment',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.DeleteModel(
            name='IncomeType',
        ),
        migrations.DeleteModel(
            name='PaymentType',
        ),
    ]
