# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManMon', '0007_auto_20170219_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='type_income',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='payment',
            name='type_payment',
            field=models.CharField(default='', max_length=200),
        ),
    ]
