# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManMon', '0008_auto_20170219_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_income', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TypePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_payment', models.CharField(max_length=200)),
            ],
        ),
    ]
