# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ManMon', '0009_typeincome_typepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeincome',
            name='income',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ManMon.Income'),
        ),
        migrations.AddField(
            model_name='typepayment',
            name='payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ManMon.Payment'),
        ),
    ]
