# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 15:45
from __future__ import unicode_literals

import ManMon.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ManMon', '0010_auto_20170219_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeincome',
            name='income',
            field=models.ForeignKey(default=ManMon.models.Income, on_delete=django.db.models.deletion.CASCADE, to='ManMon.Income'),
        ),
        migrations.AlterField(
            model_name='typepayment',
            name='payment',
            field=models.ForeignKey(default=ManMon.models.Payment, on_delete=django.db.models.deletion.CASCADE, to='ManMon.Payment'),
        ),
    ]
