# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManMon', '0012_auto_20170219_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeincome',
            name='income',
        ),
        migrations.RemoveField(
            model_name='typepayment',
            name='payment',
        ),
    ]
