# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManMon', '0013_auto_20170219_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='earning',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='buy_thing',
            field=models.FloatField(default=0),
        ),
    ]
