# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManMon', '0015_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pub_time',
            field=models.TimeField(default="00:00:00"),
        ),
        migrations.AlterField(
            model_name='account',
            name='pub_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
