# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 03:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170122_1511'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='hoice',
        ),
    ]
