# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 03:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170203_0338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hoice',
            old_name='choice_text',
            new_name='hoice_text',
        ),
    ]
