# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 04:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20170203_0405'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hoice',
            new_name='Choice',
        ),
    ]
